### ISSUE TITLE
最後のActionを取得する際、次のアクションがないためIndex out of range になる

### ISSUE THREAD

**Issue by kitadakyou** [kitadakyou/vipassanacco#7]
例外をキャッチして、適切な処理を書く

**Comment by kkebo** [comment]
例外を発生させてキャッチするよりも `ActionList.getNextAction` の戻り値の型を `Action | undefined` にして `this.actions.find(x => x.startTime > now)` を返すとかの方がスマートそうだなと思いました。

**Comment by kitadakyou** [comment]
その方が良いね。最初、存在しないときnullとかfalseを返すことを考えていて、それだと挙動として分かりづらい(覚えておかないと行けない)から、明示的にcatchしようとしてたんだよね。

**Comment by kkebo** [comment]
こういう場合、例外で返しちゃうと TypeScript だと外から見ても例外が発生することが分からないので、上で書いてるみたいに戻り値の型を見れば一目瞭然な方がわかりやすいんじゃないかなと個人的には思ってました。大体エディタの補完でわかりますし。

**Comment by kitadakyou** [comment]
確かに、nullが返ってくるのも例外を吐くのも、知っておかなきゃいけないって意味だと同じレベルで不親切だね。。
1日1時間程度しかコンピューターは触れないので、対応は気長にお待ちください

**Comment by kkebo** [comment]
TypeScript の場合型定義 or 型推論されているので知ってなくても null が返ってくることはわかるんじゃないですか？

**Comment by kitadakyou** [comment]
これは趣味の問題なんだけど、「次のアクションがない」という場合に関数にどのような挙動をさせるかで
- null を返して次のアクションがないことを呼び出し元に知らせる
- 例外をそのまま返す(コントローラーにその後の処理を委ねる)
の2パターン思いついて、後から読んだときに比較的分かりやすいのは後者かな？と思っていて、
その後
- find 関数を使って undefined を返す
っていう方法を言われて、それが一番しっくりきたかな、というだけの理由で、TypeScriptの機能的にはどれを取っても実現は可能です。

ただ、可読性や汎用性を考えるとその実装が一番いいかなと思っただけです。

**Comment by kitadakyou** [comment]
#9 で対応
